import { Camera } from "./behaviours/Camera";
import { CircleCollider, EdgeCollider, BoxCollider } from "./behaviours/Collider";
import { PhysicsWorld } from "./behaviours/PhysicsWorld";
import { RigidBody } from "./behaviours/RigidBody";
import { Rotatable } from "./behaviours/Rotatable";
import { ShapeRectRenderer } from "./behaviours/ShapeRectRenderer";
import { Walkable } from "./behaviours/Walkable";
import { BlockPrefabBinding } from "./bindings/BlockPrefabBinding";
import { MainRolePrefabBinding } from "./bindings/MainRolePrefabBinding";
import { registerBehaviourClass, GameEngine } from "./engine";
import { AnimationRenderer } from "./engine/AnimationRenderer";
import { BitmapRenderer } from "./engine/BitmapRenderer";
import { TextRenderer } from "./engine/TextRenderer";
import { Transform } from "./engine/Transform";
registerBehaviourClass(Camera);
registerBehaviourClass(CircleCollider);
registerBehaviourClass(EdgeCollider);
registerBehaviourClass(BoxCollider);
registerBehaviourClass(PhysicsWorld);
registerBehaviourClass(RigidBody);
registerBehaviourClass(Rotatable);
registerBehaviourClass(ShapeRectRenderer);
registerBehaviourClass(Walkable);
registerBehaviourClass(BlockPrefabBinding);
registerBehaviourClass(MainRolePrefabBinding);
registerBehaviourClass(AnimationRenderer);
registerBehaviourClass(BitmapRenderer);
registerBehaviourClass(TextRenderer);
registerBehaviourClass(Transform);
const engine = new GameEngine();
engine.start();
